### ISSUE TITLE
 MemoryError: std::bad_alloc

### ISSUE THREAD

**Issue by SiHengHeHSH** [skyhehe123/VoxSeT#23]
Traceback (most recent call last):
  File "/home/hsh/下载/VoxSeT/tools/train_utils/train_utils.py", line 114, in train_model
    accumulated_iter = train_one_epoch(
  File "/home/hsh/下载/VoxSeT/tools/train_utils/train_utils.py", line 26, in train_one_epoch
    batch = next(dataloader_iter)
  File "/home/hsh/anaconda3/envs/voxset2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/hsh/anaconda3/envs/voxset2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/hsh/anaconda3/envs/voxset2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hsh/anaconda3/envs/voxset2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hsh/下载/VoxSeT/tools/../pcdet/datasets/kitti/kitti_dataset.py", line 427, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)
  File "/home/hsh/下载/VoxSeT/tools/../pcdet/datasets/dataset.py", line 148, in prepare_data
    data_dict = self.data_processor.forward(
  File "/home/hsh/下载/VoxSeT/tools/../pcdet/datasets/processor/data_processor.py", line 220, in forward
    data_dict = cur_processor(data_dict=data_dict)
  File "/home/hsh/下载/VoxSeT/tools/../pcdet/datasets/processor/data_processor.py", line 125, in transform_points_to_voxels
    self.voxel_generator = VoxelGeneratorWrapper(
  File "/home/hsh/下载/VoxSeT/tools/../pcdet/datasets/processor/data_processor.py", line 36, in __init__
    self._voxel_generator = VoxelGenerator(
MemoryError: std::bad_alloc
python-BaseException

**Comment by zgh1349786296** [comment]
I have also encountered this problem, how should I deal with it?

**Comment by YouthZCC** [comment]
Is the problem solved？What is the solution？

**Comment by ghost** [comment]
Hi, I would like to ask if there is any progress on this issue, thanks.

**Comment by JokinYang** [comment]
This problem same as #11 mentationed. I solved this by following #11`s procedure.
